/*"C:\\Users\\Tahsin Mubarak\\Documents\\NetBeansProjects\\JavaApplication7\\src\\password.csv"
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import com.opencsv.CSVReader;
import com.opencsv.exceptions.CsvValidationException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author Tahsin Mubarak
 */
public class admin extends javax.swing.JFrame {
    String filePath;
    String path;

    /**
     * Creates new form admin
     */
    public admin() {
        initComponents();
        setSize(500, 300);
        setResizable(false);
        setLocationRelativeTo(null);
        filePath = new File("").getAbsolutePath();
        path=filePath+"\\src\\password.csv";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Login");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 0, 480, 82);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Username:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(88, 124, 116, 22);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(230, 128, 144, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 166, 104, 14);
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(230, 166, 144, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(230, 219, 144, 25);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lufthansa_A380_first_class_cabin.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 520, 310);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 520, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String a = jTextField1.getText();
String b = new String(jPasswordField1.getPassword());
int flag=0;
       CSVReader reader=null;
                String[] pass;
                try{
                    reader=new CSVReader(new FileReader(path));
                    while((pass=reader.readNext())!=null){
                        if(pass[0].equals(a)&&pass[1].equals(b)){
                        flag=1;
                        break;
                        }
                    }
                }catch (FileNotFoundException fileNotFoundException){
                    fileNotFoundException.printStackTrace();
                }catch (IOException ioException){
                    ioException.printStackTrace();
                }catch (CsvValidationException csvValidationException){
                    csvValidationException.printStackTrace();
                }


                if (flag==1){
                    JOptionPane.showMessageDialog(null, "Logged in");
                 jTextField1.setText(null);
                 jPasswordField1.setText(null);
                JFrame frame = new JFrame();
                frame.add(new Switch().getpanel());
                frame.setVisible(true);
                frame.setSize(610, 340);
                frame.setResizable(false);
                frame.setLocationRelativeTo(null);
            }
                else{
                 JOptionPane.showMessageDialog(null,"Error Logging in");
                 jTextField1.setText(null);
                 jPasswordField1.setText(null);
                }

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
     public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run(){
                new admin().setVisible(true);
            }
        });
    }
 javax.swing.JPanel getpanel()
        {return  jPanel1;}   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
